MODEL:
  NAME: 'resnet50'
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/williamramirez/Desktop/paper_willy/will9426-automatic-Region-proposal-for-cars-in-Re-id-models/custom_model/pretrained/resnet50.pth'
  DEVICE_ID: ('0,1')
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  REDUCTION: 16
  MULTI_NUMS: 1
  EMBED_NUM: 512 #1024
  TEMPERATURE: 10.0
  MODE: 'DPRC'
  REFINE: 'BASE'

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 0

DATASETS:
  NAMES: ('vric')
  ROOT_DIR: ('/home/williamramirez/Desktop/codigoswilliam/proyecto_tesis/vehicle_data')
  PROPOSAL_DIR: ('/home/williamramirez/Desktop/codigoswilliam/proyecto_tesis/vehicle_data/masks/VRIC/')
  PROPOSAL_NUM: 8

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 512 #1000
  BASE_LR: 0.000175

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005
  TRIPLET_LOSS_WEIGHT: 0.3
  CLUSTER_LOSS_WEIGHT: 1
  ID_LOSS_WEIGHT: 2.0

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 8

  STEPS: [30,50,70,90,110,130]
  GAMMA: 0.5

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 15
  LOG_PERIOD: 100
  EVAL_PERIOD: 15

TEST:
  IMS_PER_BATCH: 16
  RE_RANKING: 'yes'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: /home/desktop/codigos_william/results/PGAN/VRIC/test1

